version: '3.4'

services:
  web:
    build: .
    hostname: dev-reservations
    ports:
      - "80:80"
      - "443:443"
    links:
      - mysql_reservations
    environment:
      - TERM=xterm
      - TZ=Europe/Zurich
      - PERL5LIB=/opt/dinfo/lib/perl
      - DATABASE_BOTTIN_NAME=bottin
      - DATABASE_BOTTIN_HOST=mysql_reservations
      - DATABASE_BOTTIN_USER=reservations
      - DATABASE_BOTTIN_PWD=reservations
      - DATABASE_DINFO_NAME=dinfo
      - DATABASE_DINFO_HOST=mysql_reservations
      - DATABASE_DINFO_USER=reservations
      - DATABASE_DINFO_PWD=reservations
      - TEQUILA_HOST=test-tequila.epfl.ch
      - MOCK_ORACLE=1

  mysql_reservations:
    image: mysql:5.5
    hostname: mysql-reservations
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=reservations
      - MYSQL_USER=reservations
      - MYSQL_PASSWORD=reservations
    volumes:
      - ./conf/docker/initdb:/docker-entrypoint-initdb.d
    ports:
      - "23306:3306"