keybase_secrets: >-
  {{       _keybase_secrets_prod    if inventory_environment == "prod"
      else _keybase_secrets_preprod if inventory_environment == "test"
      else None }}
_keybase_secrets_prod: >-
    {{ lookup('file', '/keybase/team/epfl_resrvations/secrets-prod.yml') | from_yaml }}
_keybase_secrets_preprod: >-
    {{ lookup('file', '/keybase/team/epfl_resrvations/secrets-test.yml') | from_yaml }}

reservations_image_name: >-
    os-docker-registry.epfl.ch/{{ openshift_namespace }}/reservations:{{ inventory_environment }}

reservations_hostname: >-
    {{ "reservations-preprod.epfl.ch" if inventory_environment == "test"
       else "reservations.epfl.ch" }}
