- tags: always
  include_vars: reservations-vars.yml

- include_tasks:
    file: reservations-build-tasks.yml
    apply:
      tags:
        - reservations.build
  tags:
  - reservations.build
  - reservations.promote

- include_tasks:
    file: reservations-openshift-run-tasks.yml
    apply:
      tags:
        - reservations.run
  tags:
  - reservations.run
