- name: "{{ reservations_image_name }} Docker image: local build"
  when: inventory_environment == "test"
  docker_image:
    name: "{{ reservations_image_name }}"
    source: build
    force_source: true
    build:
      path: '{{ resasible_dir }}/..'
  register: reservations_image

- when:
    - inventory_environment == "test"
    # We shouldn't need this, as idempotent pushes should be de-duped by their SHA256...
    # But that doesn't quite work as of now, so we do.
    - (reservations_image | default({})) is changed
  name: "{{ reservations_image_name }} Docker image: push to OpenShift"
  docker_image:
    name: "{{ reservations_image_name }}"
    source: local
    push: true

- name: "Promote test image to production"
  when: inventory_environment == "prod"
  shell:
    cmd: |
      oc tag reservations-test/reservations:test \
             reservations-prod/reservations:prod
  tags:
    - never
    - reservations.promote
