all:
  hosts:
    openshift-test:
      openshift_namespace: svc0102t-reservations
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
      inventory_environment: test
      route_visibility: private
