all:
  vars:
      ansible_connection: local
      ansible_python_interpreter: "{{ resasible_dir }}/ansible-deps-cache/bin/python3"
  hosts:
    reservations-test:
      openshift_namespace: reservations-test
      inventory_environment: test
